In [ ]:
import pandas as pd

# File paths
amazon_path = "Amazon.csv"
google_path = "GOOG.csv"
netflix_path = "NFLX.csv"

# Read CSV files
amazon_df = pd.read_csv(amazon_path)
google_df = pd.read_csv(google_path)
netflix_df = pd.read_csv(netflix_path)

# Function to clean stock data
def clean_data(df, name):
    print(f"\n--- Cleaning {name} Dataset ---")
    
    # 1. Remove duplicate rows (if any)
    df = df.drop_duplicates()
    
    # 2. Handle missing values
    df = df.dropna()   # removes rows with any missing values
    
    
    # 3. Convert 'Date' column to datetime format
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    
    # 4. Remove rows where 'Date' could not be parsed (NaT)
    df = df.dropna(subset=['Date'])
    print("Removing rows",df.dropna())
    
    # 5. Reset index after cleaning
    df = df.reset_index(drop=True)
    
    print(" Cleaning done!")
    print("Shape after cleaning:", df.shape)
    return df

# Clean all datasets
amazon_clean = clean_data(amazon_df, "Amazon")
google_clean = clean_data(google_df, "Google")
netflix_clean = clean_data(netflix_df, "Netflix")

print(amazon_clean.head())
print(google_clean.head())
print(netflix_clean.head())

# Sort Amazon, Google, and Netflix data by Date (newest first) 
amazon_sorted = amazon_clean.sort_values(by="Date", ascending=False) 
google_sorted = google_clean.sort_values(by="Date", ascending=False) 
netflix_sorted = netflix_clean.sort_values(by="Date", ascending=False)

print(amazon_sorted.head(10))
print(google_sorted.head(10))
print(netflix_sorted.head(10))

--- Cleaning Amazon Dataset ---
 Cleaning done!
Shape after cleaning: (6099, 7)

--- Cleaning Google Dataset ---
 Cleaning done!
Shape after cleaning: (2347, 7)

--- Cleaning Netflix Dataset ---
 Cleaning done!
Shape after cleaning: (5422, 7)
        Date      High       Low      Open     Close     Volume  Adj Close
0 1997-12-31  5.041667  4.843750  4.875000  5.020833  4446000.0   5.020833
1 1998-01-02  5.000000  4.796875  5.000000  4.958333  1660800.0   4.958333
2 1998-01-05  4.937500  4.708333  4.885417  4.750000  3590400.0   4.750000
3 1998-01-06  4.875000  4.666667  4.697917  4.838542  4174800.0   4.838542
4 1998-01-07  4.833333  4.692708  4.833333  4.781250  2725200.0   4.781250
        Date       Open       High        Low      Close  Adj Close    Volume
0 2015-01-02  26.378078  26.490770  26.133251  26.168653  26.168653  28951268
1 2015-01-05  26.091366  26.144720  25.582764  25.623152  25.623152  41196796
2 2015-01-06  25.679497  25.738087  24.983908  25.029282  25.029282  57998800
3 2015-01-07  25.280592  25.292759  24.914099  24.986401  24.986401  41301082
4 2015-01-08  24.831326  25.105074  24.482782  25.065184  25.065184  67071641
        Date      Open      High       Low     Close  Adj Close     Volume
0 2002-05-23  1.156429  1.242857  1.145714  1.196429   1.196429  104790000
1 2002-05-24  1.214286  1.225000  1.197143  1.210000   1.210000   11104800
2 2002-05-28  1.213571  1.232143  1.157143  1.157143   1.157143    6609400
3 2002-05-29  1.164286  1.164286  1.085714  1.103571   1.103571    6757800
4 2002-05-30  1.107857  1.107857  1.071429  1.071429   1.071429   10154200
           Date         High          Low         Open        Close  \
6098 2022-03-25  3307.370117  3247.489990  3280.000000  3282.010010
6097 2022-03-24  3282.370117  3201.000000  3274.989990  3272.989990
6096 2022-03-23  3327.399902  3253.739990  3274.100098  3268.159912
6095 2022-03-22  3323.340088  3233.979980  3236.110107  3297.780029
6094 2022-03-21  3261.679932  3191.060059  3222.419922  3229.830078
6093 2022-03-18  3231.879883  3120.219971  3136.260010  3225.010010
6092 2022-03-17  3149.969971  3042.800049  3052.810059  3144.780029
6091 2022-03-16  3063.000000  2947.070068  2970.000000  3062.080078
6090 2022-03-15  2959.699951  2840.000000  2857.000000  2947.330078
6089 2022-03-14  2949.000000  2817.679932  2919.620117  2837.060059

         Volume    Adj Close
6098  1584383.0  3282.010010
6097  2834900.0  3272.989990
6096  2790600.0  3268.159912
6095  3204300.0  3297.780029
6094  3326900.0  3229.830078
6093  5141300.0  3225.010010
6092  3646700.0  3144.780029
6091  4247900.0  3062.080078
6090  3779200.0  2947.330078
6089  3704300.0  2837.060059
           Date        Open        High         Low       Close   Adj Close  \
2346 2024-04-30  167.380005  169.869995  164.500000  164.639999  164.639999
2345 2024-04-29  170.770004  171.380005  167.059998  167.899994  167.899994
2344 2024-04-26  175.990005  176.419998  171.399994  173.690002  173.690002
2343 2024-04-25  153.360001  158.279999  152.768005  157.949997  157.949997
2342 2024-04-24  159.089996  161.389999  158.820007  161.100006  161.100006
2341 2024-04-23  158.589996  160.479996  157.964996  159.919998  159.919998
2340 2024-04-22  156.009995  159.184998  155.660004  157.949997  157.949997
2339 2024-04-19  157.750000  157.990005  153.910004  155.720001  155.720001
2338 2024-04-18  156.925003  158.485001  156.210007  157.460007  157.460007
2337 2024-04-17  157.190002  158.681000  156.134995  156.880005  156.880005

        Volume
2346  29420800
2345  35914600
2344  56500800
2343  36197800
2342  19485700
2341  16115400
2340  17243900
2339  20063900
2338  14016100
2337  16237800
           Date        Open        High         Low       Close   Adj Close  \
5421 2023-12-05  450.700012  456.390015  449.579987  455.149994  455.149994
5420 2023-12-04  460.989990  461.200012  451.200012  453.899994  453.899994
5419 2023-12-01  473.170013  475.230011  464.600006  465.739990  465.739990
5418 2023-11-30  475.309998  478.589996  470.420013  473.970001  473.970001
5417 2023-11-29  479.000000  480.989990  474.489990  477.190002  477.190002
5416 2023-11-28  478.109985  480.500000  475.950012  479.000000  479.000000
5415 2023-11-27  479.029999  482.000000  475.350006  479.170013  479.170013
5414 2023-11-24  477.109985  480.399994  475.200012  479.559998  479.559998
5413 2023-11-22  476.799988  482.700012  476.559998  478.000000  478.000000
5412 2023-11-21  472.630005  477.019989  471.209991  474.950012  474.950012

       Volume
5421  3261100
5420  5157700
5419  4338100
5418  4287300
5417  2855500
5416  2890200
5415  3625900
5414  1404700
5413  2841600
5412  2997700